name: "Actions Release"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: 打包并发布
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: 检查缓存
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: 设置环境变量
      run: npm config set puppeteer_skip_chromium_download=true
    - name: 安装依赖
      run: npm ci
    - name: 打包
      run: npm run build:win
    - name: 压缩
      run: makecab dist/acfunlive.exe dist/acfunlive.cab
    - name: 上传
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/acfunlive.cab
        asset_name: acfunlive_win_$tag.cab
        tag: ${{ github.ref }}
        overwrite: true
