name: "Release Win"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: npm config set puppeteer_skip_chromium_download=true
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build:win
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: acfunlive.exe
        asset_name: acfunlive.exe
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
